/**
 * DEMO 1: Simple - FIXED VERSION (CI-Resilient)
 * 
 * Generated by FLAKES Fixer Agent
 * Original: button-click.fail.spec.ts
 * 
 * FLAKES Categories Fixed: L (Latency) + A (Async)
 * 
 * Fixes applied:
 *   ✅ All page.click/fill actions properly awaited (A)
 *   ✅ All short timeouts removed — using Playwright defaults (L)
 *   ✅ Non-retrying isVisible() replaced with auto-retrying expect() (A)
 *   ✅ Timing assertion replaced with behavioral assertion (L)
 *   ✅ Fixed sleep replaced with auto-retrying assertion (L)
 *   ✅ Value capture timing fixed by awaiting fill first (A)
 * 
 * @tags @pass @simple @latency @async @fixed
 */

import { test, expect } from '@playwright/test';
import * as os from 'os';

const BASE_URL = 'https://gauravkhurana.in/test-automation-play/';

// 🔍 Minimal logging - called once per suite
function logEnvironmentInfo() {
  console.log(`\n🖥️ ${process.platform} | CI: ${process.env.CI || 'local'} | Cores: ${os.cpus().length} | RAM: ${Math.round(os.freemem() / 1024 / 1024 / 1024)}GB free\n`);
}

test.describe('Simple Demo - Fixed Tests @pass @fixed', () => {

  // Log environment once at start
  test.beforeAll(() => logEnvironmentInfo());

  test('should click button - with proper timeout for CI', async ({ page }) => {
    await page.goto(BASE_URL);
    
    // ✅ FIX [L]: Use default timeout (5s) — accommodates slow CI
    const basicTab = page.locator('button', { hasText: 'Basic' });
    await expect(basicTab).toBeVisible();
    
    await basicTab.click();
    
    const enabledButton = page.getByRole('button', { name: 'Enabled Button' });
    // ✅ FIX [L]: Default timeout handles CI latency
    await expect(enabledButton).toBeVisible();
    await enabledButton.click();
  });

  test('should fill form - with auto-retrying assertion', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    
    await page.getByPlaceholder('Enter your first name').fill('Test');
    
    // ✅ FIX [L]: Remove fixed sleep + short timeout
    // Auto-retrying assertion handles timing — no sleep needed
    await expect(page.getByPlaceholder('Enter your first name')).toHaveValue('Test');
  });

  test('should verify navigation - behavioral assertion instead of timing', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    await page.getByPlaceholder('Enter your first name').fill('Performance Test');
    
    // ✅ FIX [L]: Assert behavior, not timing
    // CI machines vary 2-10x in speed — timing assertions are always flaky
    await expect(page.getByPlaceholder('Enter your first name')).toHaveValue('Performance Test');
  });

  test('should select dropdown - with proper timeouts', async ({ page }) => {
    // ✅ FIX [L]: Use default navigation timeout (30s)
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    
    const dropdown = page.getByTestId('country-select');
    // ✅ FIX [L]: Default timeout (5s) instead of 50ms
    await expect(dropdown).toBeVisible();
    await dropdown.click();
    await expect(page.getByRole('option', { name: 'Canada' })).toBeVisible();
  });

  test('should interact with checkbox - with proper timeouts', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    
    const checkbox = page.getByRole('checkbox').first();
    
    // ✅ FIX [L]: Default timeout (5s) instead of 30ms
    await expect(checkbox).toBeVisible();
    await checkbox.check();
    await expect(checkbox).toBeChecked();
    await checkbox.uncheck();
    await expect(checkbox).not.toBeChecked();
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // 🅰️ ASYNC + LATENCY FIXES - Every action awaited, every timeout safe
  // ═══════════════════════════════════════════════════════════════════════════

  test('A1: properly awaited fill + default timeout', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    
    const input = page.getByPlaceholder('Enter your first name');
    
    // ✅ FIX [A]: Await fill so it completes before assertion
    // ✅ FIX [L]: Use default timeout (5s) for auto-retry
    await input.fill('Async Test');
    await expect(input).toHaveValue('Async Test');
  });

  test('A2: properly awaited click + default timeout', async ({ page }) => {
    await page.goto(BASE_URL);
    
    // ✅ FIX [A]: Await click so tab content loads before assertion
    await page.click('button:has-text("Basic")');
    
    // ✅ FIX [L]: Default timeout gives CI enough time
    const input = page.getByPlaceholder('Enter your first name');
    await expect(input).toBeVisible();
  });

  test('A3: properly awaited click + auto-retrying assertion', async ({ page }) => {
    await page.goto(BASE_URL);
    
    // ✅ FIX [A]: Await click to ensure completion
    await page.click('button:has-text("Basic")');
    
    // ✅ FIX [A]: Use auto-retrying expect() instead of one-shot isVisible()
    // isVisible() checks ONCE — expect().toBeVisible() retries for 5s
    const input = page.getByPlaceholder('Enter your first name');
    await expect(input).toBeVisible();
  });

  test('A4: all actions properly awaited in sequence', async ({ page }) => {
    await page.goto(BASE_URL);
    
    // ✅ FIX [A]: Await every action — they execute in order
    await page.click('button:has-text("Basic")');
    await page.getByPlaceholder('Enter your first name').fill('Race');
    await page.getByPlaceholder('Enter your last name').fill('Condition');
    
    // ✅ FIX [L]: Default timeout for assertion
    await expect(page.getByPlaceholder('Enter your first name')).toHaveValue('Race');
  });

  test('A5: await fill before capturing value', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.click('button:has-text("Basic")');
    
    const input = page.getByPlaceholder('Enter your first name');
    
    // ✅ FIX [A]: Await fill so value is set before we read it
    await input.fill('Promise Value');
    
    // ✅ FIX [A]: Use auto-retrying assertion instead of one-shot inputValue()
    await expect(input).toHaveValue('Promise Value');
  });

  test('A6: properly awaited click + auto-retrying visibility check', async ({ page }) => {
    await page.goto(BASE_URL);
    
    const start = Date.now();
    
    // ✅ FIX [A]: Await click to ensure completion
    await page.click('button:has-text("Basic")');
    
    // ✅ FIX [A]: Use auto-retrying expect() instead of one-shot isVisible()
    const input = page.getByPlaceholder('Enter your first name');
    await expect(input).toBeVisible();
    
    const elapsed = Date.now() - start;
    console.log(`⏱️ Completed in ${elapsed}ms — element is visible`);
  });

});
